# Generated by Django 4.1 on 2022-08-28 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='ID',
            new_name='sensor',
        ),
        migrations.RenameField(
            model_name='measurement',
            old_name='result',
            new_name='temperature',
        ),
    ]
