# Generated by Django 4.1 on 2022-08-28 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0004_rename_date_measurement_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensor',
            options={'ordering': ['pk'], 'verbose_name': 'Датчик', 'verbose_name_plural': 'Датчики'},
        ),
    ]
