# Generated by Django 4.1 on 2022-08-29 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0007_alter_measurement_sensor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='sensor',
        ),
        migrations.AddField(
            model_name='measurement',
            name='sensor_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='measurement.sensor', verbose_name='ID датчика'),
            preserve_default=False,
        ),
    ]
